// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type PluginListParams = { 
/**
 * Additional roots to use when discovering repo-scoped marketplaces. Home-scoped
 * marketplaces are always considered.
 */
additionalRoots?: Array<AbsolutePathBuf> | null, };
